name: CI

on:
  push:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkput repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkput repository
        uses: actions/checkout@v3

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Install clippy
        run: rustup component add clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkput repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --locked

  coverage:
    if: github.ref == 'refs/heads/main'
    needs: [build, lint, test]

    uses: ./.github/workflows/coverage.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pages:
    if: github.ref == 'refs/heads/main'
    needs: [build, lint, test]
    permissions:
      contents: write

    uses: ./.github/workflows/pages.yml
